os:
  - linux
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install pipenv
  - pipenv sync --dev
script:
  - pipenv run pytest --codestyle --flakes --cov=./
after_success:
  - pipenv run codecov