os:
  - linux
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install pipenv
  - pipenv install --dev --ignore-pipfile --system
  - pipenv install pytest-cov --ignore-pipfile
  - pipenv install codecov --ignore-pipfile
script:
  - pipenv run pytest --cov=./
after_success:
  - pipenv run codecov