os:
  - linux
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install .
  - pip install pytest-cov
  - pip install codecov
script:
  - pytest --cov=./
after_success:
  - codecov